apiVersion: v1
kind: Namespace
metadata:
  name: sample-go-api
spec:
  finalizers:
    - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: sample-go-api-api
    app.kubernetes.io/part-of: sample-go-api
  name: sample-go-api-api
  namespace: sample-go-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-go-api-api
      app.kubernetes.io/part-of: frisk
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample-go-api-api
        app.kubernetes.io/part-of: sample-go-api
    spec:
      containers:
        - name: sample-go-api-api
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
          image: garreeoke/sample-go-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http-port
              protocol: TCP
          resources: {}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: sample-go-api-api
    app.kubernetes.io/part-of: sample-go-api
  name: sample-go-api-api
  namespace: sample-go-api
spec:
  ports:
    - name: http-port
      port: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: sample-go-api-api
    app.kubernetes.io/part-of: sample-go-api
  sessionAffinity: None
  type: LoadBalancer
